# Generated by Django 5.2.1 on 2025-09-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_role_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INITIATOR', 'Initiator'), ('APPROVER_1', 'Approver Level 1'), ('APPROVER_2', 'Approver Level 2'), ('APPROVER_3', 'Approver Level 3'), ('APPROVER_4', 'Approver Level 4'), ('APPROVER_5', 'Approver Level 5'), ('EXECUTOR', 'Executor')], default='INITIATOR', max_length=20),
        ),
    ]
