# Generated by Django 5.2.1 on 2025-09-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_add_request_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestapproval',
            options={'ordering': ['created_at'], 'verbose_name': 'Request Approval', 'verbose_name_plural': 'Request Approvals'},
        ),
        migrations.RemoveField(
            model_name='requestapproval',
            name='approval_level',
        ),
    ]
