# Generated by Django 5.2.1 on 2025-09-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='depositor_name',
            field=models.CharField(blank=True, help_text='Name of the person making the deposit', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depositor_phone',
            field=models.CharField(blank=True, help_text='Phone number of the depositor', max_length=20, null=True),
        ),
    ]
