# Generated by Django 5.2.6 on 2025-09-22 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('TRANSACTION_CREATED', 'Transaction Created'), ('TRANSACTION_UPDATED', 'Transaction Updated'), ('TRANSACTION_CANCELLED', 'Transaction Cancelled'), ('DEPOSIT_APPROVED', 'Deposit Approved'), ('DEPOSIT_REJECTED', 'Deposit Rejected'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_UPDATED', 'Account Updated'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('CITY_CREATED', 'City Created'), ('CITY_UPDATED', 'City Updated'), ('SYSTEM_ACTION', 'System Action')], max_length=30)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
