# Generated by Django 5.2.1 on 2025-09-25 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approverassignment',
            options={'ordering': ['transaction_type', 'approver__username'], 'verbose_name': 'Approver Assignment', 'verbose_name_plural': 'Approver Assignments'},
        ),
        migrations.AlterUniqueTogether(
            name='approverassignment',
            unique_together={('transaction_type', 'approver')},
        ),
        migrations.RemoveField(
            model_name='approverassignment',
            name='approval_level',
        ),
    ]
